name: SlimefunTimeit
authors:
  - balugaq
main: com.balugaq.sftimeit.core.SlimefunTimeit
website: https://github.com/balugaq/SlimefunTimeit
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
