name: SlimefunTimeit
authors:
  - balugaq
main: com.balugaq.sftimeit.SlimefunTimeit
website: https://github.com/balugaq/SlimefunTimeit
version: ${project.version}
api-version: 1.20
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
