name: Publish build

on:
  push:
    branches:
      - official-version

jobs:
  publish:
    name: Upload build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20

      - name: Build with Maven
        run: mvn -B package

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: SlimefunTimeit
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.ref_name }}"
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            build.zip

